//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap antenna {
            get {
                object obj = ResourceManager.GetObject("antenna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balance {
            get {
                object obj = ResourceManager.GetObject("balance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of selection.
        /// </summary>
        internal static string BaseTreeView_SelectNext_End_of_selection {
            get {
                return ResourceManager.GetString("BaseTreeView_SelectNext_End_of_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more element found.
        /// </summary>
        internal static string BaseTreeView_SelectNext_No_more_element_found {
            get {
                return ResourceManager.GetString("BaseTreeView_SelectNext_No_more_element_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(Hidden).
        /// </summary>
        internal static string BoxControl_RefreshControl_ {
            get {
                return ResourceManager.GetString("BoxControl_RefreshControl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call {
            get {
                object obj = ResourceManager.GetObject("call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call_icon {
            get {
                object obj = ResourceManager.GetObject("call_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circular_arrow {
            get {
                object obj = ResourceManager.GetObject("circular_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_closed {
            get {
                object obj = ResourceManager.GetObject("folder_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_opened {
            get {
                object obj = ResourceManager.GetObject("folder_opened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functional analysis.
        /// </summary>
        internal static string FunctionalBlockControl_HandleMouseDoubleClick_functional_analysis {
            get {
                return ResourceManager.GetString("FunctionalBlockControl_HandleMouseDoubleClick_functional_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add this function to the display view.
        /// </summary>
        internal static string GraphView_AddFunction_Cannot_add_this_function_to_the_display_view {
            get {
                return ResourceManager.GetString("GraphView_AddFunction_Cannot_add_this_function_to_the_display_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display function.
        /// </summary>
        internal static string GraphView_AddFunction_Cannot_display_function {
            get {
                return ResourceManager.GetString("GraphView_AddFunction_Cannot_display_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap in_icon {
            get {
                object obj = ResourceManager.GetObject("in_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap in_out_icon {
            get {
                object obj = ResourceManager.GetObject("in_out_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interface_icon {
            get {
                object obj = ResourceManager.GetObject("interface_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interface_icon1 {
            get {
                object obj = ResourceManager.GetObject("interface_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internal_icon {
            get {
                object obj = ResourceManager.GetObject("internal_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap model_icon {
            get {
                object obj = ResourceManager.GetObject("model_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functional view.
        /// </summary>
        internal static string NameSpacesTreeNode_ShowFunctionalViewHandler_functional_view {
            get {
                return ResourceManager.GetString("NameSpacesTreeNode_ShowFunctionalViewHandler_functional_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm moving the namespace.
        /// </summary>
        internal static string NameSpaceTreeNode_AcceptDrop_Confirm_moving_the_namespace {
            get {
                return ResourceManager.GetString("NameSpaceTreeNode_AcceptDrop_Confirm_moving_the_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will move the namespace, are you sure ? .
        /// </summary>
        internal static string NameSpaceTreeNode_AcceptDrop_This_will_move_the_namespace__are_you_sure___ {
            get {
                return ResourceManager.GetString("NameSpaceTreeNode_AcceptDrop_This_will_move_the_namespace__are_you_sure___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functional view.
        /// </summary>
        internal static string NameSpaceTreeNode_ShowFunctionalViewHandler_functional_view {
            get {
                return ResourceManager.GetString("NameSpaceTreeNode_ShowFunctionalViewHandler_functional_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap out_icon {
            get {
                object obj = ResourceManager.GetObject("out_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move the corresponding paragraph?.
        /// </summary>
        internal static string ParagraphTreeNode_AcceptDrop_Are_you_sure_you_want_to_move_the_corresponding_paragraph_ {
            get {
                return ResourceManager.GetString("ParagraphTreeNode_AcceptDrop_Are_you_sure_you_want_to_move_the_corresponding_para" +
                        "graph_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move a paragraph in its sub paragraphs.
        /// </summary>
        internal static string ParagraphTreeNode_AcceptDrop_Cannot_move_a_paragraph_in_its_sub_paragraphs {
            get {
                return ResourceManager.GetString("ParagraphTreeNode_AcceptDrop_Cannot_move_a_paragraph_in_its_sub_paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move paragraph.
        /// </summary>
        internal static string ParagraphTreeNode_AcceptDrop_Move_paragraph {
            get {
                return ResourceManager.GetString("ParagraphTreeNode_AcceptDrop_Move_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parameter_icon {
            get {
                object obj = ResourceManager.GetObject("parameter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin {
            get {
                object obj = ResourceManager.GetObject("pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_mark {
            get {
                object obj = ResourceManager.GetObject("question_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap read_icon {
            get {
                object obj = ResourceManager.GetObject("read_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redefines_icon {
            get {
                object obj = ResourceManager.GetObject("redefines_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap req_icon {
            get {
                object obj = ResourceManager.GetObject("req_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph not added.
        /// </summary>
        internal static string RequirementSetControl_AcceptDrop_Paragraph_not_added {
            get {
                return ResourceManager.GetString("RequirementSetControl_AcceptDrop_Paragraph_not_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph not added to the requirement set because it already belongs to it.
        /// </summary>
        internal static string RequirementSetControl_AcceptDrop_Paragraph_not_added_to_the_requirement_set_because_it_already_belongs_to_it {
            get {
                return ResourceManager.GetString("RequirementSetControl_AcceptDrop_Paragraph_not_added_to_the_requirement_set_becau" +
                        "se_it_already_belongs_to_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speed_control {
            get {
                object obj = ResourceManager.GetObject("speed_control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state diagram.
        /// </summary>
        internal static string StateControl_HandleMouseDoubleClick_state_diagram {
            get {
                return ResourceManager.GetString("StateControl_HandleMouseDoubleClick_state_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to override the state machine ? .
        /// </summary>
        internal static string StateMachineTreeNode_AcceptDrop_Are_you_sure_you_want_to_override_the_state_machine___ {
            get {
                return ResourceManager.GetString("StateMachineTreeNode_AcceptDrop_Are_you_sure_you_want_to_override_the_state_machi" +
                        "ne___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override state machine.
        /// </summary>
        internal static string StateMachineTreeNode_AcceptDrop_Override_state_machine {
            get {
                return ResourceManager.GetString("StateMachineTreeNode_AcceptDrop_Override_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state diagram.
        /// </summary>
        internal static string StateMachineTreeNode_ViewDiagram_state_diagram {
            get {
                return ResourceManager.GetString("StateMachineTreeNode_ViewDiagram_state_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state diagram.
        /// </summary>
        internal static string StateTreeNode_ViewDiagram_state_diagram {
            get {
                return ResourceManager.GetString("StateTreeNode_ViewDiagram_state_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create event.
        /// </summary>
        internal static string StaticTimeLineControl_TimeLineControl_DragDrop_Cannot_create_event {
            get {
                return ResourceManager.GetString("StaticTimeLineControl_TimeLineControl_DragDrop_Cannot_create_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate variable default value.
        /// </summary>
        internal static string StaticTimeLineControl_TimeLineControl_DragDrop_Cannot_evaluate_variable_default_value {
            get {
                return ResourceManager.GetString("StaticTimeLineControl_TimeLineControl_DragDrop_Cannot_evaluate_variable_default_v" +
                        "alue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub sequence execution report.
        ///.
        /// </summary>
        internal static string SubSequenceTreeNode_RunHandler_ {
            get {
                return ResourceManager.GetString("SubSequenceTreeNode_RunHandler_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string SubSequenceTreeNode_RunHandler__seconds {
            get {
                return ResourceManager.GetString("SubSequenceTreeNode_RunHandler__seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution report.
        /// </summary>
        internal static string SubSequenceTreeNode_RunHandler_Execution_report {
            get {
                return ResourceManager.GetString("SubSequenceTreeNode_RunHandler_Execution_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test duration : .
        /// </summary>
        internal static string SubSequenceTreeNode_RunHandler_Test_duration___ {
            get {
                return ResourceManager.GetString("SubSequenceTreeNode_RunHandler_Test_duration___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test_icon {
            get {
                object obj = ResourceManager.GetObject("test_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state diagram.
        /// </summary>
        internal static string ToolStripShowStateMachine_OnClick_state_diagram {
            get {
                return ResourceManager.GetString("ToolStripShowStateMachine_OnClick_state_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap train {
            get {
                object obj = ResourceManager.GetObject("train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrainMoving {
            get {
                object obj = ResourceManager.GetObject("TrainMoving", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap type_icon {
            get {
                object obj = ResourceManager.GetObject("type_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unpin {
            get {
                object obj = ResourceManager.GetObject("unpin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state diagram.
        /// </summary>
        internal static string VariableTreeNode_ViewDiagram_state_diagram {
            get {
                return ResourceManager.GetString("VariableTreeNode_ViewDiagram_state_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wheel {
            get {
                object obj = ResourceManager.GetObject("wheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model view.
        /// </summary>
        internal static string Window_Dictionary_model_view {
            get {
                return ResourceManager.GetString("Window_Dictionary_model_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string Window_Refresh__none_ {
            get {
                return ResourceManager.GetString("Window_Refresh__none_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more marking to show.
        /// </summary>
        internal static string Window_toolStripButton1_Click_No_more_marking_to_show {
            get {
                return ResourceManager.GetString("Window_toolStripButton1_Click_No_more_marking_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more markings.
        /// </summary>
        internal static string Window_toolStripButton1_Click_No_more_markings {
            get {
                return ResourceManager.GetString("Window_toolStripButton1_Click_No_more_markings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection history view.
        /// </summary>
        internal static string Window_Window_Selection_history_view {
            get {
                return ResourceManager.GetString("Window_Window_Selection_history_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System test view.
        /// </summary>
        internal static string Window_Window_System_test_view {
            get {
                return ResourceManager.GetString("Window_Window_System_test_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap write_icon {
            get {
                object obj = ResourceManager.GetObject("write_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
